In [160]:
#importing the libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [161]:
#load the dataset

span_data = pd.read_csv('spam.csv')   

In [162]:
span_data

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [163]:
span_data['Category'].apply(lambda x: 1 if x == 'spam' else 0)

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: Category, Length: 5572, dtype: int64

In [164]:
span_data

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [165]:
#Recreating the new column 'span' based on the 'Category' column
span_data['span'] = span_data['Category'].apply(lambda x: 1 if x == 'spam' else 0)


In [166]:
span_data

Category                                            Message  span
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [167]:
#display the first few rows of the DataFrame
span_data.head()

Category                                            Message  span
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [168]:
#display the information about the DataFrame
span_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
 2   span      5572 non-null   int64 
dtypes: int64(1), object(2)
memory usage: 130.7+ KB


In [169]:
# Displaying the statistical summary of the numerical data
span_data.describe()

span
count  5572.000000
mean      0.134063
std       0.340751
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

In [170]:
# Displaying the last few rows of the DataFrame
span_data.tail()

Category                                            Message  span
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

In [171]:
from sklearn.feature_extraction.text import CountVectorizer

In [172]:
x=span_data['Message']
y=span_data['span']

In [173]:
vectorizer = CountVectorizer()
X_vectorized = vectorizer.fit_transform(x)
X_vectorized = X_vectorized.toarray()


In [174]:
X_vectorized

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 8709))

In [175]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_vectorized, y, test_size=0.2, random_state=42)


In [176]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4457, 8709)
(1115, 8709)
(4457,)
(1115,)


In [177]:
from sklearn.naive_bayes import GaussianNB

In [178]:
gaussian_model = GaussianNB()
gaussian_model.fit(X_train, y_train)

GaussianNB()

In [179]:
y_prod = gaussian_model.predict(X_test)

In [180]:
y_prod

array([0, 0, 0, ..., 0, 0, 1], shape=(1115,))

In [181]:
y_test[:10]

3245    0
944     0
1044    0
2484    0
812     0
2973    0
2991    0
2942    0
230     0
1181    0
Name: span, dtype: int64

In [182]:
y_prod[:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0])

In [183]:
y_test[:10] 

3245    0
944     0
1044    0
2484    0
812     0
2973    0
2991    0
2942    0
230     0
1181    0
Name: span, dtype: int64

In [184]:
y_test[:20]

3245    0
944     0
1044    0
2484    0
812     0
2973    0
2991    0
2942    0
230     0
1181    0
1912    0
1992    0
5435    0
4805    0
401     1
1859    0
1344    0
2952    0
501     0
3337    0
Name: span, dtype: int64

In [185]:
y_prod[:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0])

In [186]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_prod)

0.9067264573991032

In [187]:
from sklearn.naive_bayes import MultinomialNB


  

In [188]:
multinomial_model = MultinomialNB()
multinomial_model.fit(X_train, y_train)


MultinomialNB()

In [189]:
y_pred = multinomial_model.predict(X_test)

In [190]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(1115,))

In [191]:
y_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [192]:
y_test[:10]

3245    0
944     0
1044    0
2484    0
812     0
2973    0
2991    0
2942    0
230     0
1181    0
Name: span, dtype: int64

In [193]:
accuracy_score(y_test, y_pred)

0.9856502242152466

In [194]:
emails = [
    'How are you',
    'Free free free get upto 20% discount',
    'Limited time offer',
    'Congratulations, you have won a lottery!'
]

In [195]:
emails_vectorized = vectorizer.transform(emails)

In [196]:
emails_vectorized = emails_vectorized.toarray()
emails_vectorized

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4, 8709))

In [197]:
multinomial_model.predict(emails_vectorized)

array([0, 1, 0, 1])